name = "bddr-tong-log"
main = "src/index.js"
compatibility_date = "2026-07-06"

[vars]
DATA_R2_PREFIX = "bddr/data"
ALLOWED_BROWSER_ORIGINS = "https://ledonchung.github.io,http://127.0.0.1:5501"

[[r2_buckets]]
binding = "DATA_BUCKET"
bucket_name = "capstone"

[[d1_databases]]
binding = "DB"
database_name = "bddr_logs"
database_id = "19e67f61-e51d-436b-bcfc-a57dfd45de9f"





